# -*- coding: utf-8 -*-
"""parse_sut

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/144HxeyPHQYpFLeDdG_DihZDiIxZfCSY4
"""

import requests
from bs4 import BeautifulSoup

headers = {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"}
r = requests.get("https://cabinet.sut.ru/raiting_sait", headers=headers)

r.text

soup = BeautifulSoup(r.text, 'lxml')

soup.find('table', class_="table")

table1 = soup.find('tbody', class_=None)

trs = table1.find_all('tr')

name = []
fac = []
year = []
grade = []

for tr in trs:
    tds = tr.find_all('td')
    name.append(tds[1].text.strip())
    fac.append(tds[2].text.strip())
    year.append(tds[3].text.strip())
    grade.append(tds[4].text.strip())